# Generated by Django 4.2.4 on 2023-10-23 06:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AcademyVideo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="The unique identifier of this video.",
                        unique=True,
                        verbose_name="uuid",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="The title of this video.",
                        max_length=255,
                        null=True,
                        verbose_name="title",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="The description of this video.", null=True, verbose_name="description"
                    ),
                ),
                (
                    "video_link",
                    models.CharField(
                        blank=True,
                        help_text="The video link of this video.",
                        max_length=255,
                        null=True,
                        verbose_name="video link",
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        help_text="The thumbnail of this video.",
                        null=True,
                        upload_to="thumbnails/",
                        verbose_name="thumbnail",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Designates whether this video is active.", verbose_name="is active"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Webinar",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="The unique identifier of this video.",
                        unique=True,
                        verbose_name="uuid",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="The name of this webinar.",
                        max_length=255,
                        null=True,
                        verbose_name="name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="The description of this webinar.", null=True, verbose_name="description"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="The image of this webinar.",
                        null=True,
                        upload_to="webinar/",
                        verbose_name="image",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        blank=True, help_text="The date of this webinar.", null=True, verbose_name="date"
                    ),
                ),
                (
                    "time",
                    models.TimeField(
                        blank=True, help_text="The time of this webinar.", null=True, verbose_name="time"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="The location of this webinar.",
                        max_length=255,
                        null=True,
                        verbose_name="location",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
