# Generated by Django 4.2.4 on 2023-10-23 10:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("education", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="academyvideo",
            name="is_active",
        ),
    ]
