# Generated by Django 4.2.4 on 2024-02-24 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jsonform.models.fields
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Signal",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, help_text="Unique identifier for this object.", unique=True
                    ),
                ),
                (
                    "entry",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The entry price of the signal.",
                        max_digits=10,
                        verbose_name="entry",
                    ),
                ),
                (
                    "take_profit",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The take profit price of the signal.",
                        max_digits=10,
                        verbose_name="take profit",
                    ),
                ),
                (
                    "stop_loss",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The stop loss price of the signal.",
                        max_digits=10,
                        verbose_name="stop loss",
                    ),
                ),
                (
                    "term",
                    models.CharField(
                        choices=[("long", "Long"), ("short", "Short")],
                        default="long",
                        help_text="The term of the signal.",
                        max_length=5,
                        verbose_name="term",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[("buy", "Buy"), ("sell", "Sell")],
                        default="buy",
                        help_text="The action of the signal.",
                        max_length=5,
                        verbose_name="action",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="The description of the signal.", null=True, verbose_name="description"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Designates whether this signal is active.", verbose_name="is active"
                    ),
                ),
                (
                    "targets",
                    django_jsonform.models.fields.ArrayField(
                        base_field=models.EmailField(max_length=254),
                        blank=True,
                        help_text="Profit targets",
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="author",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
