# Generated by Django 4.2.4 on 2024-02-24 15:02

from django.db import migrations, models
import django_jsonform.models.fields


class Migration(migrations.Migration):
    dependencies = [
        ("trading", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signal",
            name="entry",
            field=models.DecimalField(
                decimal_places=8, help_text="The entry price of the signal.", max_digits=10, verbose_name="entry"
            ),
        ),
        migrations.AlterField(
            model_name="signal",
            name="stop_loss",
            field=models.DecimalField(
                decimal_places=8,
                help_text="The stop loss price of the signal.",
                max_digits=10,
                verbose_name="stop loss",
            ),
        ),
        migrations.AlterField(
            model_name="signal",
            name="take_profit",
            field=models.DecimalField(
                decimal_places=8,
                help_text="The take profit price of the signal.",
                max_digits=10,
                verbose_name="take profit",
            ),
        ),
        migrations.AlterField(
            model_name="signal",
            name="targets",
            field=django_jsonform.models.fields.ArrayField(
                base_field=models.DecimalField(decimal_places=8, max_digits=10),
                blank=True,
                help_text="Profit targets",
                null=True,
                size=None,
            ),
        ),
    ]
