# Generated by Django 4.2.4 on 2024-02-28 04:03

from django.db import migrations, models
import django_jsonform.models.fields


class Migration(migrations.Migration):
    dependencies = [
        ("trading", "0005_subscriptionplan_subscription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriptionplan",
            name="notification_channels",
            field=django_jsonform.models.fields.ArrayField(
                base_field=models.CharField(
                    choices=[("telegram", "Telegram"), ("whatsapp", "WhatsApp"), ("email", "Email"), ("sms", "SMS")],
                    default="telegram",
                    max_length=10,
                ),
                help_text="Notification channels, choices are telegram, whatsapp, email, sms.",
                size=None,
            ),
        ),
    ]
