# Generated by Django 4.2.4 on 2024-02-28 05:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trading", "0006_alter_subscriptionplan_notification_channels"),
    ]

    operations = [
        migrations.AddField(
            model_name="signal",
            name="pair_base",
            field=models.CharField(
                default="EUR", help_text="The base pair of the signal.", max_length=10, verbose_name="pair base"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="signal",
            name="pair_quote",
            field=models.CharField(
                default="USD", help_text="The quote pair of the signal.", max_length=10, verbose_name="pair quote"
            ),
            preserve_default=False,
        ),
    ]
