# Generated by Django 4.2.4 on 2024-03-06 05:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trading", "0008_alter_subscriptionplan_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriptionplan",
            name="ordering",
            field=models.PositiveIntegerField(
                default=1, help_text="The ordering of the subscription plan.", verbose_name="ordering"
            ),
        ),
    ]
