# Generated by Django 4.2.4 on 2024-03-06 05:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("trading", "0011_alter_subscriptionplan_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscriptionplan",
            options={"ordering": ["-ordering"]},
        ),
    ]
