# Generated by Django 4.2.4 on 2024-03-06 07:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trading", "0013_alter_subscriptionplan_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionplan",
            name="coming_soon",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether this subscription plan is coming soon.",
                verbose_name="coming soon",
            ),
        ),
    ]
