# Generated by Django 4.2.4 on 2024-03-09 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("trading", "0014_subscriptionplan_coming_soon"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscriptions_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="created by",
            ),
        ),
    ]
