# Generated by Django 4.2.4 on 2023-10-27 15:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("trading", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TopPerformingBot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, help_text="Unique identifier for this object.", unique=True
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="The description of this top performing bot.",
                        null=True,
                        verbose_name="description",
                    ),
                ),
                (
                    "price",
                    models.CharField(
                        blank=True,
                        help_text="The price of this top performing bot.",
                        max_length=255,
                        null=True,
                        verbose_name="price",
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        blank=True,
                        help_text="The period of this top performing bot.",
                        max_length=255,
                        null=True,
                        verbose_name="period",
                    ),
                ),
                (
                    "bot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="top_performing_bots",
                        to="trading.bot",
                        verbose_name="bot",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
