# Generated by Django 4.2.4 on 2023-10-27 16:56

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):
    dependencies = [
        ("trading", "0002_topperformingbot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="copytradingguide",
            name="description",
            field=tinymce.models.HTMLField(
                blank=True,
                help_text="The description of this copy trading guide.",
                null=True,
                verbose_name="description",
            ),
        ),
    ]
