# Generated by Django 4.2.4 on 2023-10-27 21:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("trading", "0003_alter_copytradingguide_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="BotlabBot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, help_text="Unique identifier for this object.", unique=True
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, help_text="The name of this bot.", max_length=255, null=True, verbose_name="name"
                    ),
                ),
                (
                    "name_of_broker",
                    models.CharField(
                        blank=True,
                        help_text="The name of broker of this bot.",
                        max_length=255,
                        null=True,
                        verbose_name="name of broker",
                    ),
                ),
                (
                    "server_name",
                    models.CharField(
                        blank=True,
                        help_text="The server name of this bot.",
                        max_length=255,
                        null=True,
                        verbose_name="server name",
                    ),
                ),
                (
                    "investor_login",
                    models.CharField(
                        blank=True,
                        help_text="The investor login of this bot.",
                        max_length=255,
                        null=True,
                        verbose_name="investor login",
                    ),
                ),
                (
                    "investor_password",
                    models.CharField(
                        blank=True,
                        help_text="The investor password of this bot.",
                        max_length=255,
                        null=True,
                        verbose_name="investor password",
                    ),
                ),
                (
                    "terminal",
                    models.CharField(
                        blank=True,
                        help_text="The terminal of this bot.",
                        max_length=255,
                        null=True,
                        verbose_name="terminal",
                    ),
                ),
                (
                    "test_commencement_date",
                    models.DateField(
                        blank=True,
                        help_text="The test commencement date of this bot.",
                        null=True,
                        verbose_name="test commencement date",
                    ),
                ),
                (
                    "is_delisted",
                    models.BooleanField(
                        default=False, help_text="Designates whether this bot is delisted.", verbose_name="is delisted"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
