# Generated by Django 4.2.4 on 2023-10-30 12:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("trading", "0005_accountupgradepaymentrequest"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscriptionplan",
            options={"ordering": ["-created_at"]},
        ),
    ]
