# Generated by Django 4.2.4 on 2023-10-30 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trading", "0006_alter_subscriptionplan_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="accountscreeningrequest",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="accountscreeningrequest",
            name="is_approved",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether this account screening request is approved.",
                verbose_name="is approved",
            ),
        ),
    ]
