# Generated by Django 4.2.4 on 2023-10-30 15:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("trading", "0007_alter_accountscreeningrequest_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscriptionplan",
            options={"ordering": ["created_at"]},
        ),
    ]
