# Generated by Django 4.2.4 on 2023-10-22 07:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_remove_verificationcode_phone_number_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "has_trading_experience",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether this user has trading experience.",
                        verbose_name="has trading experience",
                    ),
                ),
                (
                    "ref_id",
                    models.CharField(
                        blank=True,
                        help_text="The referral id of this user.",
                        max_length=255,
                        null=True,
                        verbose_name="referral id",
                    ),
                ),
                (
                    "amount_range_to_trade_with",
                    models.CharField(
                        blank=True,
                        help_text="The amount range to trade with.",
                        max_length=255,
                        null=True,
                        verbose_name="amount range to trade with",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this user profile.",
                        unique=True,
                        verbose_name="uuid",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "profile",
                "verbose_name_plural": "profiles",
            },
        ),
    ]
