# Generated by Django 4.2.4 on 2024-02-24 10:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_remove_user_is_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="type",
            field=models.CharField(
                choices=[("user", "User"), ("admin", "Admin")],
                default="user",
                help_text="The type of user.",
                max_length=5,
                verbose_name="type",
            ),
        ),
    ]
