# Generated by Django 4.2.4 on 2024-02-28 05:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_user_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="nickname",
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name="nickname"),
        ),
    ]
